import Head from 'next/head'
import { loadVeg } from '../../lib/loadVeg.js'
import { loadRecipes } from '../../lib/loadRecipes.js'
import Recipe from '../../components/Recipe.js'
import { React, useState } from 'react'
import Select from 'react-select'
import Link from 'next/link'

const currentMonth = new Date().getMonth()

export async function getStaticProps() {
    const allVeg = await loadVeg()
    const currentMonthData = allVeg[currentMonth]
    const currentMonthVegArray = currentMonthData.food.map((veg) => veg.name)
    const currentMonthsRecipes = await loadRecipes(currentMonthVegArray)

    const selectOptions = currentMonthVegArray.map((opt) => ({
        label: opt,
        value: opt,
    }))
    return {
        props: { currentMonthsRecipes, selectOptions },
        revalidate: 604800, //seconds in week
    }
}

export default function Home({ currentMonthsRecipes, selectOptions }) {
    const [userChoice, setUserChoice] = useState('')
    console.log(currentMonthsRecipes)
    return (
        <>
            <Head>
                <title>Recipes</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h2 className="text-2xl text-center font-bold">Recipes Page</h2>
            <Select
                options={selectOptions}
                onChange={(opt) => setUserChoice(opt.value)}
            />
            <Link
                href={'/recipes/' + userChoice.toLowerCase().replace(' ', '-')}
            >
                SEARCH
            </Link>
            <div className="grid gap-6 grid-cols-1 md:grid-cols-2 max-w-6xl m-auto">
                {currentMonthsRecipes.hasOwnProperty('fetched') &&
                currentMonthsRecipes.fetched.length !== 0
                    ? currentMonthsRecipes.fetched.map((recipe) => (
                          <Recipe key={recipe.label} props={recipe} />
                      ))
                    : 'We have exceeded our API calls. Please try again in a minute!'}
            </div>
        </>
    )
}
