import Head from 'next/head'
import { loadVeg } from '../../lib/loadVeg.js'
import { loadRecipes } from '../../lib/loadRecipes.js'
import Recipe from '../../components/Recipe.js'

const currentMonth = new Date().getMonth()

export async function getStaticProps() {
    const allVeg = await loadVeg()
    const currentMonthData = allVeg[currentMonth]
    const currentMonthVegArray = currentMonthData.food.map((veg) => veg.name)

    const currentMonthsRecipes = await loadRecipes(currentMonthVegArray)

    // Pass data to the page via props
    return {
        props: { currentMonthsRecipes },
        revalidate: 604800, //seconds in week
    }
}

export default function Home({ currentMonthsRecipes }) {
    return (
        <div className="bg-pink-200">
            <Head>
                <title>Recipes</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Recipes Page</h1>
                <form>
                    
                    </form>
                <div> 
                    {currentMonthsRecipes.fetched.map((recipe) => (
                        <Recipe key={recipe.label} props={recipe} />
                    ))}
                </div>
            </main>

            <footer></footer>
        </div>
    )
}
