import { useState, useContext } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { loadVeg } from '../lib/loadVeg.js'
import GlobalMonth from '../lib/GlobalMonth'

// const currentMonth = new Date().getMonth()

export async function getStaticProps() {
    const allMonths = await loadVeg()

    //const currentMonthData = allMonths[currentMonth]
    return { props: { allMonths } }
}

export default function Home({ allMonths }) {
    const currentMonth = useContext(GlobalMonth)
    const currentMonthData = allMonths[currentMonth]

    return (
        <div className="bg-pink-200">
            <Head>
                {/* <title>{currentMonthData.name}</title> */}
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="container mx-auto">
                    <h1 className="text-2xl text-blue-600">
                        {' '}
                        Seasonal Calendar{' '}
                    </h1>
                    <p>{currentMonthData.name}</p>
                    <div className="grid gap-4 grid-cols-3 lg:grid-cols-4 ">
                        {currentMonthData.food.slice(0, 12).map((veg) => (
                            <div
                                key={veg.name}
                                className="flex flex-col justify-center items-center"
                            >
                                <div className="h-24 w-24 md:w-40 md:h-40 lg:w-48 lg:h-48 2xl:w-64 2xl:h-64">
                                    <Image
                                        src={veg.imageUrlSmall}
                                        width={300}
                                        height={300}
                                        alt={veg.name}
                                        className="object-cover h-full w-full rounded-full"
                                    />
                                </div>

                                <h2>{veg.name}</h2>
                            </div>
                        ))}
                    </div>
                </div>
            </main>

            <footer></footer>
        </div>
    )
}
