import Head from 'next/head'

export default function Home() {
    return (
        <div className="bg-pink-200">
            <Head>
                <title>NEED TO CHANGE THIS LATER</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className="text-2xl text-blue-600">Fruits</h1>
            </main>

            <footer></footer>
        </div>
    )
}
